title: Anthony & Cheryl
description: Wedding celebration — save the date and find all the details here.
url: https://nichollswedding.co.uk
baseurl: ""

wedding_date: Saturday, 24 April 2027
venue_name: Cogges Manor Farm, Witney
countdown_datetime: "2027-04-24T13:00:00+01:00"
rsvp:
  day:
    deadline: 1st March 2027
    url: https://forms.gle/TYaC1gbCh69rhgCw6
  evening:
    deadline: 1st February 2027
    url: https://forms.gle/mLFNgaRh1h63CqHb9
email: hello@nichollswedding.co.uk

exclude:
  - Gemfile
  - README.md
  - vendor
